### ISSUE TITLE
Support plural date/time

### ISSUE THREAD

**Issue by panther7** [laedit/new-tab-moment#171]
Actualy, date `D. M Y` returns `8. listopad 2022`, correct is `8. listopadu 2022`

Example for correct format:
```js
var dateTimeFormat = new Intl.DateTimeFormat(navigator.language, {
  day: 'numeric',
  month: 'long',
  year: 'numeric',
});
console.log(dateTimeFormat.format(Date.now()));
```

**Comment by laedit** [comment]
Thanks for your feedback, I will investigate when I can 👍

**Comment by laedit** [comment]
So I already use `Intl.DateTimeFormat` but didn't know that the result could be influenced by the other parameters.
Will fix that.

**Comment by laedit** [comment]
The new version is submitted and will be published in the next 24h.

**Comment by laedit** [comment]
Thanks again for your feedback! :)
