### ISSUE TITLE
000:34:24 displayed at night

### ISSUE THREAD

**Issue by alexeyqu** [laedit/new-tab-moment#174]
Hi, just a small bug report from me.

Sometimes (IIRC after 12am) the extension displays hours as 000 as hours.
I have `H:M:S` set as time format.

![image](https://user-images.githubusercontent.com/7394728/202589535-c0bb3b36-453f-4afc-b246-fa022aed87ef.png)

**Comment by laedit** [comment]
Thanks for the feedback!
This should be fixed quickly :)

**Comment by laedit** [comment]
The new version is submitted and should be published in the next 24h.
