### ISSUE TITLE
Chromium Version

### ISSUE THREAD

**Issue by eeriemyxi** [laedit/new-tab-moment#181]
Any plans for a Chromium version of this plugin? I like the simplicity and custom CSS that this extension provides, but I couldn't say the same for any of the popular extensions for Chromium browsers.
![image](https://user-images.githubusercontent.com/86738916/211785840-656e3934-c262-418b-aae5-8b48ba680dc5.png)

**Comment by laedit** [comment]
Thanks for your feedback, I love what you've done with the addon! :)
I haven't thought of that but it should be possible.
Do you need it hosted in a store (chrome web store for example) or a zip in the releases should do the trick?

**Comment by eeriemyxi** [comment]
> Thanks for your feedback, I love what you've done with the addon! :)

Thank you, I appreciate your comments. 

> I haven't thought of that but it should be possible. Do you need it hosted in a store (chrome web store for example) or a zip in the releases should do the trick?

Either would work; however, adding it to the Chrome Web Store might gain some publicity if you'd like that.

**Comment by laedit** [comment]
In that case I will only provide a zip, I prefer to stay away from anything google related.
No promise but I will try to work on it this weekend.

**Comment by laedit** [comment]
Can you try this [version](https://github.com/laedit/new-tab-moment/suites/10501070729/artifacts/521054832)?
You will have to unzip it (twice thanks to github artifacts) and activate the developer mode on the extensions page of your favorite chromium browser.
There is one error on loading due to a manifest key not supported by chromium but that will not break the extension.

**Comment by eeriemyxi** [comment]
![explorer_3O6Fe9SNtO.png](https://user-images.githubusercontent.com/86738916/213858869-07c55e53-9250-4356-b0e7-ddc7f95ba72f.png)

It's working wonderfully! Wish Microsoft allowed for more customization though; but the contemporary customization settings are still far more than I'd expect from them, thanks to them for that perhaps.

Thank you for this minimal extension and for the Chromium version. I'd appreciate adding custom JS code injection in future if possible as well, but that's up to you whether you'd want to work on it, no pressure nor expectation from my side. I think somehow bringing that in will make up for endless customization though.

**Comment by laedit** [comment]
Excellent!
I will publish the new version soon.

About the js code injection, can you create another issue describing your use case?

**Comment by laedit** [comment]
Can I use your screenshot to promote the custom css functionality (I am not good with css)?

**Comment by eeriemyxi** [comment]
> Excellent!
> I will publish the new version soon.

Thankful to know!

> About the js code injection, can you create another issue describing your use case?

Yes sure, but not right now; I have some huge events incoming. I will make sure to open an issue after about 2/3 months.

To summarize, implementing custom JS code injection would allow people to create their own widgets, connect to APIs to add them to their new tab. If the extension gets famous, it would be possible for someone to instead of forking the extension, do something with this feature to allow for endless customizations

**Comment by eeriemyxi** [comment]
> Can I use your screenshot to promote the custom css functionality (I am not good with css)?

Of course you can :). Here's a slightly better version: ![explorer_3fr4wWbfVr.png](https://user-images.githubusercontent.com/86738916/213927448-9f419f5b-6335-458a-98eb-15292dee802c.png)

I am using Pulse Browser (Firefox without things that should not be their without asking) with [Sweet_Pop!](https://github.com/PROxZIMA/Sweet-Pop) Custom CSS theme.

CSS Code I used (results will be slightly different on Chromium, you will have to either zoom-out or readjust the code):
```css
#time {
	background: -webkit-linear-gradient(360deg, #FAC536 35%, #9E00F4 50%, #F25056 65%);
	-webkit-background-clip: text;
	-webkit-text-fill-color: transparent;
}
```

**Comment by laedit** [comment]
It is finally published! https://microsoftedge.microsoft.com/addons/detail/new-tab-moment/lcacfcmcnhmjoleiabongjmbcclnogan
