### ISSUE TITLE
Custom JS Code Injection

### ISSUE THREAD

**Issue by eeriemyxi** [laedit/new-tab-moment#186]
Is it possible to add a feature where users of the extension could add their own JS code functions which would be called upon creating a new tab?

Implementing custom JS code injection feature would allow people to create their own widgets, connect to APIs to add them to their new tab. If the extension gets famous, it would be possible for someone to instead of forking the extension, do something with this feature to allow for endless customizations.

**Comment by laedit** [comment]
Thanks for the idea but I prefer to keep this extension minimal, and if users know how to develop in js it is easy to develop their own extension so I don't really see the value.
