### ISSUE TITLE
Multiple clocks

### ISSUE THREAD

**Issue by joukevandermaas** [laedit/new-tab-moment#213]
I work with people in multiple timezones and it would be useful for me to show more than one clock. They would be smaller like the weather info and optionally show the the timezone info. Example:

> 13:23 AEST (UTC+10)

Ideally I'd be able to name the extra clocks as well.

**Comment by laedit** [comment]
Thanks for your suggestion!
I like the idea but frankly I wouldn't have the time to work on it before long.
That said, a pull request is always welcome :)

**Comment by laedit** [comment]
So I've worked on it and the result is this:
![image](https://github.com/laedit/new-tab-moment/assets/871092/6429a87d-c405-4841-82f1-b6b26528c6bd)
You can have up to three additional clocks, for each select a time zone and display below the time either the time zone name, a custom name, both, or nothing (not illustrated in the above image).
Is that good for you?

**Comment by joukevandermaas** [comment]
@laedit sorry I missed this message, this looks exactly perfect for my use-case!

**Comment by laedit** [comment]
No worries, I am currently on vacation :)
Perfect, I will publish a new version in about two weeks.
