### ISSUE TITLE
Update Lato font family

### ISSUE THREAD

**Issue by duxa174** [laedit/new-tab-moment#3]
Hello. The current version of the font doesn't support Unicode characters. Can you update it to the [latest](https://www.latofonts.com/) version ? Thanks in advance.

**Comment by laedit** [comment]
Thanks, will do ASAP 😄

**Comment by laedit** [comment]
Fixed in dce5681cdfcb0ca349786b1c232879e7bd50e7dc and version 0.3, currently in review.
