### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rayman89** [laedit/new-tab-moment#4]
Would be possible to use the accuweather.com page which has a more detailed forecast IMO and have the option to show  morning evening and night and below the temperature the precipitation %?

Would it be possible to have the option to easily select an image to use as a background?

**Comment by laedit** [comment]
Thanks a lot for your interest, but this is merely a port of https://github.com/alfredxing/moment to webextension, sadly I don't have the time to add new functionalities.

That said, I will be happy of you want to propose a PR 😄 

About accuweather though, their free API is very limited (50 calls a day) so I don't think that is a great idea to go on it.

**Comment by laedit** [comment]
The accuweather will not be integrated in the addon, but it is now possible (once the 0.7 version is published) to set a background image url in the option (757b1b57026fc349f71b274544c11ef819727f6f).
